# apiVersion: v1 
# kind: Service
# metadata:
#   name: myapp-service
# spec:

#   selector:
#     app: myapp
#     type: front-end

#   type: NodePort
#   ports: 
#     targetPort: 80
#     port: 80
#     NodePort: 3000
  





apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000   # This is the NodePort field
